apiVersion: v1
kind: Service
metadata:
  name: {{ include "rproxy.fullname" . }}
  labels:
    {{- include "rproxy.labels" . | nindent 4 }}
  annotations:
    description: "Exposes and load balances the rproxy pods"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.port }}-tcp
  selector:
    {{- include "rproxy.selectorLabels" . | nindent 4 }}
