apiVersion: v2
name: rproxy
description: Reverse proxy for EPIC platform (eagle-public, eagle-admin, eagle-api, penguin-analytics)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - nginx
  - reverse-proxy
  - epic
  - eao
maintainers:
  - name: BC Gov EAO Team
home: https://github.com/bcgov/eao-nginx
sources:
  - https://github.com/bcgov/eao-nginx
